//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FisrtDay.md
{
    using System;
    using System.Collections.Generic;
    
    public partial class Companies
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Companies()
        {
            this.Buy = new HashSet<Buy>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public string INN { get; set; }
        public int CountryID { get; set; }
        public string Cheif { get; set; }
        public string Address { get; set; }
        public string CheifPhone { get; set; }
        public string Manager { get; set; }
        public string PhonePlus { get; set; }
        public string Bank { get; set; }
        public string BankAccount { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Buy> Buy { get; set; }
        public virtual Countries Countries { get; set; }
    }
}
