//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FisrtDay.md
{
    using System;
    using System.Collections.Generic;
    
    public partial class Goods
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Goods()
        {
            this.BuyAndGoods = new HashSet<BuyAndGoods>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public byte[] Picture { get; set; }
        public int CategoryID { get; set; }
        public System.DateTime DateStart { get; set; }
        public int Period { get; set; }
        public string Manufacturer { get; set; }
        public int UnitID { get; set; }
        public decimal CostUnit { get; set; }
        public double Count { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BuyAndGoods> BuyAndGoods { get; set; }
        public virtual Categories Categories { get; set; }
        public virtual Units Units { get; set; }
    }
}
